# Visit https://github.com/lowlighter/metrics/blob/master/action.yml for full reference
name: Metrics
on:
  # Schedule updates (daily)
  schedule: [{cron: "0 0 * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment:
      name: production
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Token with repo and read:user scopes
          token: ${{ secrets.METRICS_TOKEN }}

          # Options & Layout Structure
          user: DanielGodriNeto
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: America/Sao_Paulo
          
          # Achievements Plugin Setup
          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_achievements_ignored: explorer, gister, helper
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: C
          
          # Isometric Calendar
          plugin_isocalendar: no
          
          # Traffic Plugin
          plugin_traffic: yes
          
          # Languages Plugin Layout Setup
          plugin_languages: yes
          plugin_languages_limit: 8
          plugin_languages_sections: most-used
          plugin_languages_details: percentage
          
          # Followup Plugin (Calculates complete in-depth Issues & Pull Requests metrics)
          plugin_followup: yes
          plugin_followup_indepth: yes
